SELECT "C0" "STOPAL_COUNTPALL",
       "C1" "STOPAL_PALLID",
       "C2" "TOTAL_STOPAL_COUNT",
       "C0" "TOTAL_STOPAL_COUNTPALL_"
FROM
  (SELECT COUNT("CARRNO") "C0",
          "ECARRNO" "C1",
          SUM("CARRNO") "C2"
   FROM "G08T1" "G08T1"
   WHERE "MHA"='PICK'
   GROUP BY "ECARRNO") "T0"