SELECT "C0" "IMR_MHAFROM",
       "C1" "IMR_RACKFROM",
       "C2" "MCC3",
       "C3" "PRIO3",
       "C4" "COUNT_IMR_UNIASSIGN_NO",
       FIRST_VALUE("C4") OVER (PARTITION BY "C0", "C1", "C2", "C3") "SUM_"
FROM
  (SELECT "MHA" "C0",
          "RACK" "C1",
          CASE
              WHEN "ADMUNIT" IN ('TSA4N',
                                         'TSA4P',
                                         'T2A4N',
                                         'T2A4P',
                                         'TSAA1',
                                         'TSAA2',
                                         'TSA31',
                                         'TSA33',
                                         'TSAA4',
                                         'TSAA5',
                                         'TG231',
                                         'TG233',
                                         'T2A4N',
                                         'T2A4P') THEN '3SA'
              WHEN "ADMUNIT" IN ('TSB4N',
                                         'TSB4P',
                                         'TSBQ5',
                                         'TSBB1',
                                         'TSBB2',
                                         'TSBB4',
                                         'TSBB5',
                                         'TSB32',
                                         'TSB34',
                                         'T2B32',
                                         'T2B34',
                                         'T2BQ5',
                                         'T5B32',
                                         'T5B34') THEN '3SB'
          END "C2",
          SUBSTR("PRIORITY", 1, 8) "C3",
          COUNT("L54UNIQ") "C4"
   FROM "G08T1" "A_G08T1_L54",
        "L54T1" "L54T1"
   WHERE "MHA" IN ('13OCA',
                                 '13OCB')
     AND "CARRNO"="CARRNO"
   GROUP BY "MHA",
            "RACK",
            CASE
                WHEN "ADMUNIT" IN ('TSA4N',
                                           'TSA4P',
                                           'T2A4N',
                                           'T2A4P',
                                           'TSAA1',
                                           'TSAA2',
                                           'TSA31',
                                           'TSA33',
                                           'TSAA4',
                                           'TSAA5',
                                           'TG231',
                                           'TG233',
                                           'T2A4N',
                                           'T2A4P') THEN '3SA'
                WHEN "ADMUNIT" IN ('TSB4N',
                                           'TSB4P',
                                           'TSBQ5',
                                           'TSBB1',
                                           'TSBB2',
                                           'TSBB4',
                                           'TSBB5',
                                           'TSB32',
                                           'TSB34',
                                           'T2B32',
                                           'T2B34',
                                           'T2BQ5',
                                           'T5B32',
                                           'T5B34') THEN '3SB'
            END,
            SUBSTR("PRIORITY", 1, 8)) "T0"