SELECT CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT (AL1.BU_CODE_CRE_SHP, '-'), AL1.BU_TYPE_CRE_SHP), '-'), AL1.SHP_NO), '-'), AL1.LUTR_NO) AS OUTBOUNDTRIPID,
       AL7.BU_TYPE_CNEE AS BUTYPECNEE,
       (TRUNC(AL1.DSP_DATE_ACT)) AS DSPDATEACT,
       AL1.LU_ID,
       AL7.ITEM_ID,
       AL7.ORDER_ID,
       AL7.ITEM_QTY_ORD,
       AL7.ITEM_QTY_DSP,
       AL5.ITEM_QTY_PALL,
       ((AL5.ITEM_LEN/1000) * (AL5.ITEM_WID/1000) * (AL5.ITEM_HEI/1000))AS VOLM3,
       AL4.CTY_CODE,
       AL3.CTY_CODE AS CITYCODE2,
       AL2.BU_CODE_CNEE,
       AL7.BU_CODE_CNEE AS BUCODECNEE2,
       AL2.BU_CODE_DT,
       AL2.BU_TYPE_DT,
       AL1.ASTRO_ROUTE_ID,
       AL1.ASTRO_TRIP_ID,
       AL1.BU_CODE_CRE_SHP,
       AL1.BU_TYPE_CRE_SHP,
       AL2.CSM_NO,
       AL8.ORDER_TYPE,
       AL2.BU_CODE_CNOR,
       AL2.BU_TYPE_CNOR,
       AL6.PA_NO,
       (TO_CHAR((AL1.DSP_DATE_ACT + 1), 'YYYYIW')) AS DSPWEEK,
       AL9.CUSORD_NO,
       AL9.DEL_METHOD,
       AL10.CUSORD_HEADER_NO,
       AL8.CUSORD_NO_SRC,
       AL8.BU_CODE_CRE,
       AL11.DESCRIPTION,
       (TO_CHAR((AL1.DSP_DATE_ACT + 1), 'YYYYIW')) AS WEEK,
       (SUBSTR (AL6.PA_NO,
                1,
                2)) AS HFB,
       AL5.ITEM_WEI_GRO,
       (COUNT(DECODE(SUBSTR(AL1.ASTRO_ROUTE_ID, 1, 3), '514', AL13.PACKAGE_NO, '798', AL13.PACKAGE_NO))) AS PACKNO
FROM GEMINI.OUT_LOADING_UNIT_TRIP_UI AL1,
     GEMINI.OUT_CONSIGNMENT AL2,
     GEMINI.BUSINESS_UNIT AL3,
     GEMINI.BUSINESS_UNIT AL4,
     GEMINI.ITEM_SUP AL5,
     GEMINI.ITEM AL6,
     GEMINI.OUT_CONSIGNMENT_LINE_UI AL7,
     GEMINI.ORDERS AL8,
     GEMINI.ORDER_DELIVERY_GROUP AL9,
     GEMINI.CUSORD_HEADER_KEY_MAP_MHS_EU AL10,
     GEMINI.DELIVERY_METHOD AL11,
     GEMINI.OPERATIONAL_ORDER AL12,
     GEMINI.OPERATIONAL_ORDER_PACKAGE AL13
WHERE (AL8.CUSORD_NO = AL9.CUSORD_NO (+)
       AND AL8.CUSORD_NO_SRC = AL9.CUSORD_NO_SRC (+)
       AND AL8.CUSORD_NO = AL10.CUSORD_NO (+)
       AND AL8.CUSORD_NO_SRC = AL10.CUSORD_NO_SRC (+)
       AND AL9.DEL_METHOD = AL11.DEL_METHOD (+)
       AND AL8.ORDER_ID = AL12.ORDER_ID (+)
       AND AL8.ORDER_CRE = AL12.ORDER_CRE (+)
       AND AL8.BU_CODE_DT_FILL = AL12.BU_CODE_DT_FILL (+)
       AND AL8.BU_TYPE_DT_FILL = AL12.BU_TYPE_DT_FILL (+)
       AND AL12.OP_ORD_ID = AL13.OP_ORD_ID (+)
       AND AL12.BU_CODE_DT_FILL = AL13.BU_CODE_DT (+)
       AND AL12.BU_TYPE_DT_FILL = AL13.BU_TYPE_DT (+)
       AND AL1.BU_CODE_CRE_SHP =AL2.BU_CODE_CRE_SHP
       AND AL1.BU_TYPE_CRE_SHP =AL2.BU_TYPE_CRE_SHP
       AND AL1.SHP_NO =AL2.SHP_NO
       AND AL1.LUTR_NO =AL2.LUTR_NO
       AND AL1.BU_CODE_DT =AL2.BU_CODE_DT
       AND AL1.BU_TYPE_DT =AL2.BU_TYPE_DT
       AND AL1.BU_CODE_DT =AL3.BU_CODE
       AND AL1.BU_TYPE_DT =AL3.BU_TYPE
       AND AL6.ITEM_ID =AL7.ITEM_ID
       AND AL6.ITEM_TYPE =AL7.ITEM_TYPE
       AND AL5.ITEM_ID =AL7.ITEM_ID
       AND AL5.ITEM_TYPE =AL7.ITEM_TYPE
       AND AL7.BU_CODE_DT =AL8.BU_CODE_DT_FILL
       AND AL7.BU_TYPE_DT =AL8.BU_TYPE_DT_FILL
       AND AL7.ORDER_ID =AL8.ORDER_ID
       AND AL7.ORDER_CRE =AL8.ORDER_CRE
       AND AL2.BU_CODE_CRE_CSM =AL7.BU_CODE_CRE_CSM
       AND AL2.BU_TYPE_CRE_CSM =AL7.BU_TYPE_CRE_CSM
       AND AL2.CSM_NO =AL7.CSM_NO
       AND AL2.BU_CODE_DT =AL7.BU_CODE_DT
       AND AL2.BU_TYPE_DT =AL7.BU_TYPE_DT
       AND AL5.BU_CODE_SUP =AL7.BU_CODE_SUP
       AND AL5.BU_TYPE_SUP =AL7.BU_TYPE_SUP
       AND AL4.BU_CODE =AL7.BU_CODE_CNEE
       AND AL4.BU_TYPE =AL7.BU_TYPE_CNEE)
  AND ((AL1.BU_CODE_DT ='015'
        AND AL1.BU_TYPE_DT ='CDC'
        AND AL1.DSP_DATE_ACT BETWEEN (TRUNC(SYSDATE, 'IW') - 8) AND (TRUNC(SYSDATE, 'IW') - 1)
        AND AL7.ITEM_QTY_DSP>0))
GROUP BY CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT (AL1.BU_CODE_CRE_SHP, '-'), AL1.BU_TYPE_CRE_SHP), '-'), AL1.SHP_NO), '-'), AL1.LUTR_NO),
         AL7.BU_TYPE_CNEE,
         TRUNC(AL1.DSP_DATE_ACT),
         AL1.LU_ID,
         AL7.ITEM_ID,
         AL7.ORDER_ID,
         AL7.ITEM_QTY_ORD,
         AL7.ITEM_QTY_DSP,
         AL5.ITEM_QTY_PALL,
         (AL5.ITEM_LEN/1000) * (AL5.ITEM_WID/1000) * (AL5.ITEM_HEI/1000),
         AL4.CTY_CODE,
         AL3.CTY_CODE,
         AL2.BU_CODE_CNEE,
         AL2.BU_CODE_DT,
         AL2.BU_TYPE_DT,
         AL1.ASTRO_ROUTE_ID,
         AL1.ASTRO_TRIP_ID,
         AL1.BU_CODE_CRE_SHP,
         AL1.BU_TYPE_CRE_SHP,
         AL2.CSM_NO,
         AL7.BU_CODE_CNEE,
         AL8.ORDER_TYPE,
         AL2.BU_CODE_CNOR,
         AL2.BU_TYPE_CNOR,
         AL6.PA_NO,
         TO_CHAR((AL1.DSP_DATE_ACT + 1), 'YYYYIW'),
         AL9.CUSORD_NO,
         AL9.DEL_METHOD,
         AL10.CUSORD_HEADER_NO,
         AL8.CUSORD_NO_SRC,
         AL8.BU_CODE_CRE,
         AL11.DESCRIPTION,
         TO_CHAR((AL1.DSP_DATE_ACT + 1), 'YYYYIW'),
         SUBSTR (AL6.PA_NO,
                 1,
                 2), AL5.ITEM_WEI_GRO