SELECT "PARTNO" "IMH_L16_ART_NO",
       "PARTREV" "IMH_L16_SUP_NO",
       "L16QTY" "IMH_PICKQTY",
       "ORDNO" "IMH_L16_ORDNO",
       MIN("L16QTY")/4.2 "C__IMH_PICKQTY___4_2_",
       CONCAT("PARTNO", "PARTREV") "CONCATARTSUP",
       COUNT(CONCAT(CONCAT("PARTNO", "PARTREV"), "ORDNO"))/4.2 "COUNTARTSUPOL",
       SUBSTR("PARTNO", 1, 8) "ART_NO"
FROM "L16T3" "L16T3"
WHERE NOT "PARTNO" IS NULL
  AND "L16LCODE"='4'
  AND "PARTREV"<>'10000'
GROUP BY "PARTNO",
         "PARTREV",
         "L16QTY",
         "ORDNO",
         CONCAT("PARTNO", "PARTREV"),
         SUBSTR("PARTNO", 1, 8)